"""Lab-specific reason codes."""

from __future__ import annotations

from noema.actions.errors import ActionError


class LabError(ActionError):
    pass


INVALID_EXPERIMENT = "INVALID_EXPERIMENT"
INVALID_FORK = "INVALID_FORK"
INVALID_INTERVENTION = "INVALID_INTERVENTION"
UNSUPPORTED_LESION = "UNSUPPORTED_LESION"
PRODUCTION_MUTATION_FORBIDDEN = "PRODUCTION_MUTATION_FORBIDDEN"
NOT_COMPUTABLE = "NOT_COMPUTABLE"
CAPTURE_NOT_READY = "CAPTURE_NOT_READY"
BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
POLICY_DENIED = "POLICY_DENIED"
