"""Compiler reason codes."""

from __future__ import annotations

from noema.actions.errors import ActionError


class CompilerError(ActionError):
    pass


NOT_READY = "NOT_READY"
CONTROL_REQUIRED = "CONTROL_REQUIRED"
CONTROL_FAILED = "CONTROL_FAILED"
NOT_COMPUTABLE = "NOT_COMPUTABLE"
INVALID_EVIDENCE = "INVALID_EVIDENCE"
PRIVACY_PARTITION = "PRIVACY_PARTITION"
BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
OVER_MINIMIZATION = "OVER_MINIMIZATION"
POLICY_DENIED = "POLICY_DENIED"
INVALID_INTENT = "INVALID_INTENT"
