from __future__ import annotations

from noema.actions.errors import ActionError


class DeepTimeError(ActionError):
    pass


INVALID_INSTITUTION = "INVALID_INSTITUTION"
INVALID_SUCCESSION = "INVALID_SUCCESSION"
INVALID_ARTIFACT = "INVALID_ARTIFACT"
INVALID_CLAIM = "INVALID_CLAIM"
LORE_NOT_TRUTH = "LORE_NOT_TRUTH"
HIDDEN_HISTORY = "HIDDEN_HISTORY"
NARRATIVE_INVENTION = "NARRATIVE_INVENTION"
